epochs: 10
batch_size: 128
num_workers: 0
model:
  name: vit_tiny_patch16_224
  patch_size: 16
  img_size: 224
  embed_dim: 192
  depth: 12
  num_heads: 2
  mlp_ratio: 4.0
  qkv_bias: true
  drop_rate: 0.1
  attn_drop_rate: 0.1
  drop_path_rate: 0.1
  num_classes: 2
  finetune_type: full
  num_trainable_blocks: 2
optimizer:
  name: AdamW
  lr: 0.0005
  weight_decay: 0.01
scheduler:
  name: Linear
  total_epochs: 10
  warmup_epochs: 2
transform:
  resize: true
  random_rotation: 0
  horizontal_flip: false
  vertical_flip: false
  normalize: true
  mean:
  - 0.5
  - 0.5
  - 0.5
  std:
  - 0.5
  - 0.5
  - 0.5
